version: '3'
services:
  ldap_freeradius:
    build:
      context: .
      #variable .env pour les utiliser dans le dockerfile
      args:
        LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
        NOM_DE_DOMAINE: ${NOM_DE_DOMAINE}
        DC: ${DC}
        DC2: ${DC2}
        FREERADIUS_SECRETE: ${FREERADIUS_SECRETE}
    ports:
      - "80:80"
      - "389:389"
      - "1812:1812/udp"
      - "1813:1813/udp"
    command: >
           bash -c " 
               service slapd start && 
               service freeradius start && 
               /usr/local/bin/script.sh &&
               apache2ctl -DFOREGROUND "